# File: azure-pipelines.yml

jobs:
- job: BuildAndTest
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'PowerAppsTestAutomation.sln'
      feedsToUse: 'select'

  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\Microsoft.PowerApps.TestAutomation.Tests\bin\Debug\Microsoft.PowerApps.TestAutomation.Tests.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testFiltercriteria: 'TestCategory=PowerAppsTestAutomation'
      uiTests: true
      runSettingsFile: 'Microsoft.PowerApps.TestAutomation.Tests/patestautomation.runsettings'
      overrideTestrunParameters: |
        -OnlineUsername "$(OnlineUsername)" -OnlinePassword "$(OnlinePassword)" -BrowserType "$(BrowserTypeChrome)" -OnlineUrl "$(OnlineUrl)"
        -UsePrivateMode "$(UsePrivateMode)" -TestAutomationURLFilePath "$(TestAutomationURLFilePath)"
        -DriversPath "$(ChromeWebDriver)"

  - script: echo 'This is a script step.'
    displayName: 'Script Step'

  - script: echo 'Another script step.'
    displayName: 'Another Script Step'

- job: CloneRepo
  steps:
  - checkout: self
  - checkout: PowerAppsTestAutomation

- job: PowerAppsTestFrameworkAutomation
  dependsOn: BuildAndTest
  pool:
    vmImage: ${{ parameters.image }}
  variables:
  - name: PortalUrl
    value: https://make.powerapps.com/
    # Browser PrivateMode usage (true/false)
  - name: PrivateMode
    value: true
    # FileName where TestAutomationURLs are stored in JSON format
  - name: TestUrlFileName
    value: TestURLs.json
    # Project name of repo containing TestAutomationURLs (spaces should be encoded as %20)
    # Example: Contoso Test Framework --> Contoso%20Test%20Framework
  - name: LocalProjectName
    value: PowerAppsTestAutomation

  steps:
  - script: echo 'This is a script step in PowerAppsTestFrameworkAutomation job.'
    displayName: 'Script Step in PowerAppsTestFrameworkAutomation Job'
